#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoVendas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestaoVendas_db")]
	public partial class GestaoVendasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void Insertprodutos(produtos instance);
    partial void Updateprodutos(produtos instance);
    partial void Deleteprodutos(produtos instance);
    #endregion
		
		public GestaoVendasDataContext() : 
				base(global::GestaoVendas.Properties.Settings.Default.GestaoVendas_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GestaoVendasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestaoVendasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestaoVendasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestaoVendasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categoria> categoria
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<produtos> produtos
		{
			get
			{
				return this.GetTable<produtos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cliente;
		
		private string _Descricao;
		
		private EntitySet<produtos> _produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClienteChanging(int value);
    partial void OnClienteChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public categoria()
		{
			this._produtos = new EntitySet<produtos>(new Action<produtos>(this.attach_produtos), new Action<produtos>(this.detach_produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_Cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this.OnClienteChanging(value);
					this.SendPropertyChanging();
					this._Cliente = value;
					this.SendPropertyChanged("Cliente");
					this.OnClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ds_categoria", Storage="_Descricao", DbType="VarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_produtos", Storage="_produtos", ThisKey="Cliente", OtherKey="CodigoCliente")]
		public EntitySet<produtos> produtos
		{
			get
			{
				return this._produtos;
			}
			set
			{
				this._produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produtos(produtos entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_produtos(produtos entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produtos")]
	public partial class produtos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoProduto;
		
		private string _CodigoEAN;
		
		private System.Nullable<decimal> _ValorProduto;
		
		private System.Nullable<int> _CodigoCliente;
		
		private EntityRef<categoria> _categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoProdutoChanging(int value);
    partial void OnCodigoProdutoChanged();
    partial void OnCodigoEANChanging(string value);
    partial void OnCodigoEANChanged();
    partial void OnValorProdutoChanging(System.Nullable<decimal> value);
    partial void OnValorProdutoChanged();
    partial void OnCodigoClienteChanging(System.Nullable<int> value);
    partial void OnCodigoClienteChanged();
    #endregion
		
		public produtos()
		{
			this._categoria = default(EntityRef<categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_CodigoProduto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoProduto
		{
			get
			{
				return this._CodigoProduto;
			}
			set
			{
				if ((this._CodigoProduto != value))
				{
					this.OnCodigoProdutoChanging(value);
					this.SendPropertyChanging();
					this._CodigoProduto = value;
					this.SendPropertyChanged("CodigoProduto");
					this.OnCodigoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="codEAN", Storage="_CodigoEAN", DbType="VarChar(30)")]
		public string CodigoEAN
		{
			get
			{
				return this._CodigoEAN;
			}
			set
			{
				if ((this._CodigoEAN != value))
				{
					this.OnCodigoEANChanging(value);
					this.SendPropertyChanging();
					this._CodigoEAN = value;
					this.SendPropertyChanged("CodigoEAN");
					this.OnCodigoEANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valorProduto", Storage="_ValorProduto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ValorProduto
		{
			get
			{
				return this._ValorProduto;
			}
			set
			{
				if ((this._ValorProduto != value))
				{
					this.OnValorProdutoChanging(value);
					this.SendPropertyChanging();
					this._ValorProduto = value;
					this.SendPropertyChanged("ValorProduto");
					this.OnValorProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_CodigoCliente", DbType="Int")]
		public System.Nullable<int> CodigoCliente
		{
			get
			{
				return this._CodigoCliente;
			}
			set
			{
				if ((this._CodigoCliente != value))
				{
					this.OnCodigoClienteChanging(value);
					this.SendPropertyChanging();
					this._CodigoCliente = value;
					this.SendPropertyChanged("CodigoCliente");
					this.OnCodigoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_produtos", Storage="_categoria", ThisKey="CodigoCliente", OtherKey="Cliente", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.produtos.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.produtos.Add(this);
						this._CodigoCliente = value.Cliente;
					}
					else
					{
						this._CodigoCliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
